<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            color: #333;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 10px 20px;
            text-align: center;
        }
        main {
            padding: 20px;
        }
        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>

<header>
    <h1>Your Website Title</h1>
</header>

<main>
    <h2>Welcome to My Website</h2>
    <p>This is a simple, clean, and minimalist HTML template to get you started.</p>
    <p>Feel free to customize it to fit your needs!</p>
</main>

<footer>
    <p>© 2025 Your Name</p>
</footer>

</body>
</html>
